#!/busybox bash
#
#  init script for Vacuum Containers based on Docker
#  Create tar file with:
#    tar zcvf vcbusybox.tgz busybox init
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013-8. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Contacts: Andrew.McNab@cern.ch  http://www.gridpp.ac.uk/vac/
#
/busybox mkdir -p /srv /tmp /usr/local /usr/libexec /usr/bin /usr/sbin \
                  /var/cache /var/cvs /var/db /var/empty /var/lib \
                  /var/local /var/lock /var/log /var/run /var/tmp /etc
/busybox ln -s /cvmfs/cernvm-prod.cern.ch/cvm3/bin    \
               /cvmfs/cernvm-prod.cern.ch/cvm3/lib    \
               /cvmfs/cernvm-prod.cern.ch/cvm3/lib64  \
               /cvmfs/cernvm-prod.cern.ch/cvm3/opt    \
               /cvmfs/cernvm-prod.cern.ch/cvm3/sbin   /
/busybox ln -s /cvmfs/cernvm-prod.cern.ch/cvm3/usr/doc \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/etc \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/include \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/lib \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/lib64 \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/share \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/src \
               /cvmfs/cernvm-prod.cern.ch/cvm3/usr/vice /usr/
/busybox ln -s /cvmfs/cernvm-prod.cern.ch/cvm3/usr/bin/* /usr/bin
/busybox ln -s /cvmfs/cernvm-prod.cern.ch/cvm3/usr/sbin/* /usr/sbin
/busybox ln -s /cvmfs/cernvm-prod.cern.ch/cvm3/usr/libexec/* /usr/libexec
/busybox cp -a /cvmfs/cernvm-prod.cern.ch/cvm3/etc       \
               /cvmfs/cernvm-prod.cern.ch/cvm3/home      \
               /cvmfs/cernvm-prod.cern.ch/cvm3/root      /
/busybox cp -a /cvmfs/cernvm-prod.cern.ch/cvm3/var/spool \
               /cvmfs/cernvm-prod.cern.ch/cvm3/var/www   /var/
#
# Run the user_data script 
#
exec ${1:-/user_data}
